### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by hobbes7878** [DallasMorningNews/django-chartwerk#35]
So it feels to me we're getting pretty close to a stable API. Here's what I'd like to see to kick this thing over to a 1.0 release candidate.

- [ ] Deploy and test at POLITICO
- [ ] Re-deploy on DMN datalab
- [ ] Write RST docs for installation and config options

Tests I can live with as a longer term goal as well as other deploy options like a Heroku button.

Two of those three can be on me. Thoughts on the third? Stuff I'm missing?

**Comment by achavez** [comment]
Agreed on all three. We have the code in dataLab right now but haven't moved users over yet (we're waiting on CMS integration). I want to have it in production by the week of 7/10 at the very latest.

**Comment by hobbes7878** [comment]
Great. I'm going to deploy on our datalab over the next week.

At this rate, I'd like to stick a provisional date of Aug 1 on the 1.0 milestone for this and chartwerk-editor.

**Comment by hobbes7878** [comment]
@achavez What about a docs review this month. Anyone on your side willing to read through and make suggestions for clarity and content?

I had Fisher use django-chartwerk docs to install our app, but they could use another set of eyes, and I'm not sure anyone other than me has read through [chartwerk-editor docs](https://the-dallas-morning-news.gitbooks.io/chartwerk-editor/content/docs/introduction.html), which I just updated.

**Comment by achavez** [comment]
@hobbes7878 For sure. @allanjamesvestal or I will look over them sometime in the next couple of weeks.

**Comment by hobbes7878** [comment]
Checking in with you both on this. Aug. 1 still make sense to target for 1.0 milestone?

**Comment by achavez** [comment]
We're still not integrated into Serif, but I guess we shouldn't let that hold us back from a release. I've got it in dataLab and have tested it enough to be OK with a 1.0.

@allanjamesvestal?

**Comment by hobbes7878** [comment]
So I've been thinking about a strategy for releasing this, and as we're both stymied behind our platform teams, thinking maybe instead of stretching to 1.0 we should launch as a 0. release. 

Post- #45 , the API is stable, but I'd like to get more input from others for a period of time. Sounds like Tampa Bay may be interested and I know the Strib has wanted this for a while. We could reach out to both and offer some dedicated help with adoption, which I'm happy to moonlight for.

Otherwise, I think the obligatory think-piece-y Medium article (in brief) on Why Chartwerk, and we open the doors.

*That said...*

I'd still like a second read through documentation from your side before we push off. Here are the sections I'm most concerned about feedback on:

- [ ] Does the new [embed documentation](https://django-chartwerk.readthedocs.io/en/master/configuring.html#embed-code) in django-chartwerk make clear how to set up your own CMS integration?
- [ ] Does the [datamap section](https://the-dallas-morning-news.gitbooks.io/chartwerk-editor/content/docs/api/datamap.html) in chartwerk-editor convey the data schema abstraction piece at a layman's level?
- [ ] Do the [template basics](https://the-dallas-morning-news.gitbooks.io/chartwerk-editor/content/docs/template-basics.html) indeed cover the basics?
- [ ] Any sections that seem _too_ light?
 
I'd take as many folks feedback on that as you can spare.

Otherwise, that's my plan. What sucks?
